### ISSUE TITLE
Running git-hound in Azure Pipelines issue

### ISSUE THREAD

**Issue by joshjohanning** [ezekg/git-hound#12]
## Scenario:
Want to embed git-hound into a Pipeline in order to fail the build if any secrets are checked into source control

## Usage:
```yaml
steps:
- script: |
    go get github.com/ezekg/git-hound
    sudo ln -sf ~/go/bin/git-hound /usr/local/bin/git-hound
  displayName: 'install git-hound'

- script: | 
    git-hound sniff
  displayName: run git-hound
```

## Error:
...well there is no error. It just hands here and doesn't run anything. 

## Workaround* :
```yaml
steps:
- script: |
    go get github.com/ezekg/git-hound
    sudo ln -sf ~/go/bin/git-hound /usr/local/bin/git-hound
  displayName: 'install git-hound'

- script: | 
    git log -p | git-hound sniff
  displayName: run git-hound
```

*This works, but this pipes in all of the history. In the scenario I was looking to use git-hound for was to only fail the build if there are any secrets CURRENTLY checked into source control (disregarding all history that `git log -p` provides)

What I'm really trying to figure out is why nothing happens when running `git-hound sniff` in the pipeline and only works when `git log -p` is piped to it.
